### ISSUE TITLE
Monospacing issues in VS Code

### ISSUE THREAD

**Issue by kaBeech** [kaBeech/serious-shanns#39]
See #38 

'#' glyph causing monospacing issues

VSC Serious:
![VSC_Serious](https://github.com/user-attachments/assets/4fe1e473-0422-4d21-9b5b-1de20fedf957)

Vim Serious:
![Vim_Serious](https://github.com/user-attachments/assets/79cc6b95-435e-428f-a50b-0eeec683b581)

VSC Comic:
![VSC_Comic](https://github.com/user-attachments/assets/5722905d-22cc-43b5-a1d4-3489365146bb)

**Comment by kaBeech** [comment]
Okay, so it's not just the '#' glyph:

![serious_at](https://github.com/user-attachments/assets/1298f400-914c-4c30-bc05-fa49c4967f76)

![serious_i](https://github.com/user-attachments/assets/2918be31-29c1-430a-9015-1617f249fafc)

**Comment by kaBeech** [comment]
Fixed in Version 5.0.0

![serious_fixed](https://github.com/user-attachments/assets/b75ec066-a87b-46b8-9cf3-3943916ab11a)

Waiting for confirmation from @vic1707 before closing issue

**Comment by vic1707** [comment]
Hi, thx for all your hard work!

Unfortunately I think I'm missing something as the v5.0.0 didn't seem to fix anything for me 😓.

I just emptied my fonts folder and extracted the new zip file, ensured that vscode restarted, changed fonts a dozen times to ensure I wasn't doing something bad or a chache of some sort was messing with me but I still get the same issue on my machine.

<img width="882" alt="image" src="https://github.com/user-attachments/assets/89d39680-4d92-404c-889e-01b9484c05fd">

---
As for italics and capitals I have to admit I didn't pay attention but it seems to be fine
<img width="584" alt="image" src="https://github.com/user-attachments/assets/e21efbc8-e228-4236-9e64-de9b28379e78">

---
The only other issues I have is this in nvim + wezterm
<img width="187" alt="image" src="https://github.com/user-attachments/assets/3bb023f2-3766-4e8b-8617-035dece91225">
With top-padding 
<img width="182" alt="image" src="https://github.com/user-attachments/assets/e9e6aedd-feed-4c15-805c-8b0aa0860af0">
But that issue isn't present with the default terminal of macos so it may simply be an issue with wezterm or my config
<img width="332" alt="image" src="https://github.com/user-attachments/assets/91b2cf4c-6a8f-4c1d-84e8-53f36c7fa68e">

And the accentuated characters not being part of the font
<img width="52" alt="image" src="https://github.com/user-attachments/assets/87a9151b-638c-4336-845d-c3942ddb03cb">
But I don't write in french that often in VSCode so I don't really care.

**Comment by kaBeech** [comment]
Huh. I don't understand it. It was working last night. I'll take another crack at it soon.

> The only other issues I have is this in nvim + wezterm

That's weird, I've never seen that before (using Kitty). My hunch is it may have something to do with the same issue as the horizontal spacing. I'll work on fixing that first and see if it fixes this too.

> As for italics and capitals ... it seems to be fine

Excellent, pretty sure it's a me issue then. Thank you!

> And the accentuated characters not being part of the font

Yeah, I haven't added those yet. The fork I forked from didn't have them and I haven't pulled them over from Comic Shanns v2/Comic Shanns Mono yet because of the work involved in adding the Light and Italic styles for them. Though now that Comic Shanns Mono has references for the accented chars properly implemented it might not be too much work. I'll bump it a step up on the priorities list.

For now I'll share with you my dirty little secret - for accented chars I just load Serious Shanns first, then load Comic Shanns Mono as a backup:

![serious_accent](https://github.com/user-attachments/assets/5f356dd5-8211-4a54-9186-7dba962e649a)

**Comment by kaBeech** [comment]
@vic1707  Yeah, I'm not sure how I got it to work last night - I might have done something with VSC itself? To be clear, I'm seeing the same thing today that you're seeing.

Looks like the last commit that had it working correctly was [d780aa5](https://github.com/kaBeech/serious-shanns/tree/d780aa52ff7d6a9ca5a1e6f4479a8ef51eb4d27b). A workaround for now could be to use the versions from that commit (note that is before the name change to Serious Shanns - be careful when specifying the font names). [Here](https://github.com/kaBeech/serious-shanns/raw/d780aa52ff7d6a9ca5a1e6f4479a8ef51eb4d27b/SeriousSans/otf/SeriousSans.otf) is a link to download the the regular `.otf` version of the font from that time.

Obviously this misses out on the improvements made since then, including adding the NerdFont versions. You can of course [patch](https://github.com/ryanoasis/nerd-fonts#font-patcher) it yourself, or do a similar workaround as above to get both the accents and the Nerd Font icons from Comic Shanns Mono:

![serious_workaround](https://github.com/user-attachments/assets/874ca5f6-b871-40d6-97dd-118f49479bc7)

I'll look into a more permanent fix as well.

**Comment by kaBeech** [comment]
@vic1707 I think I figured it out:

![serious-fix](https://github.com/user-attachments/assets/357e643d-476b-4ce1-9efe-d40bb2ec87c5)

Could you try this one (it's just the one style) and let me know if it works?
[SeriousShannsFix.zip](https://github.com/user-attachments/files/16808653/SeriousShannsFix.zip)

**Comment by vic1707** [comment]
> @vic1707 Yeah, I'm not sure how I got it to work last night - I might have done something with VSC itself? To be clear, I'm seeing the same thing today that you're seeing.

Haha to be fair I'm somewhat happy that you were seeing the same thing as me, I would've felt so dumb otherwise 😂.

Just tried the new version
<img width="742" alt="image" src="https://github.com/user-attachments/assets/49c3faa5-4d08-4b88-94a0-2dda24f7bf32">
It works like a charm thank you!
Were the accentuated characters supposed to be included in this version, seeing that you got them working was such a great surprise 😁.

I'm curious as to what was wrong 🤔 .

**Comment by kaBeech** [comment]
> It works like a charm thank you!

You're welcome and thank you for all the help!

>Were the accentuated characters supposed to be included in this version, seeing that you got them working was such a great surprise 😁.

Haha, no, sorry to get your hopes up. I just have Comic Shanns Mono installed as a backup on my computer, so it replaces the missing char with the one from that package. I've opened up an issue (#49) for this though (no promises on when I actually add them)

> I'm curious as to what was wrong 🤔 .

It was incredibly poetic. You couldn't get to the issues page, so you opened PR #38, which added a single whitespace character to the README. I fixed it by adding a whitespace character to certain styles of the font :joy_cat: 

It seems that what had happened was I had inadvertently removed the whitespace glyph from like half the styles somehow when I was adjusting the monospacing over a year ago. VSC must have been guessing or resetting the width of the whitespace char incorrectly. The fix was just to add a blank glyph with the proper width to all styles that were missing one!

@vic1707 Are you still seeing that issue in wezterm?

**Comment by vic1707** [comment]
> Haha, no, sorry to get your hopes up.

No problem the font is already awesome you don't really need to bother imo.

 > It was incredibly poetic. You couldn't get to the issues page, so you opened PR https://github.com/kaBeech/serious-shanns/pull/38, which added a single whitespace character to the README. I fixed it by adding a whitespace character to certain styles of the font 😹

LMAO !! Poetic indeed xDDDD

Yep still the same strange behavior in wezterm with  v6
I think it has something to do with some sort of line height
The characters seems to be a bit to high
<img width="361" alt="image" src="https://github.com/user-attachments/assets/885cf22a-487c-4e28-9c58-947330d567e0">
<img width="361" alt="image" src="https://github.com/user-attachments/assets/f7ee0e6e-1dc7-4f50-a2da-7c633cc57156">
First is JetBrains Mono, then SeriousShanns Nerd Font with the rest of the config identical (which you can found [here](https://github.com/vic1707/.dotfiles/blob/main/.config/wezterm/wezterm.lua))

**Comment by vic1707** [comment]
But this behavior might be better discussed in another issue, I'll open it rn
